override:
  server:
    port: 8031
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.10.100:3306/pki_master
  api:
    aia: http://localhost:7011/api
    crl: http://localhost:7012/api
  logging:
    file:
      path: /opt/apps/pki-master/
      name: pki-root-api.log
