server:
  port: ${override.server.port}
  error:
    include-message: always
logging:
  file:
    path: ${override.logging.file.path}
    name: ${override.logging.file.name}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    sql: info
    web: info