server:
  port: 3005
  address: 127.0.0.1
  error:
    include-message: always
    include-path: always
    include-binding-errors: never
    include-exception: false
    include-stacktrace: never
spring:
  application:
    name: Revoke Certificate/Key
  jackson:
    serialization:
      indent_output: true
  mail:
    host: mail.khmer.name
    port: 465
    username:
    password:
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  mvc:
    servlet:
      path: /api
      load-on-startup: 1
  datasource:
    username: root
    password: 123123a
    url: jdbc:mysql://127.0.0.1:33088/pki
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db-migration
    clean-disabled: false
    validate-on-migrate: true
  session:
    jdbc:
      save-mode: always
      flush-mode: immediate
      cleanup-cron: 0 * * * * *
      initialize-schema: never
      table-name: tbl_cluster_SPRING_SESSION
      platform: mysql
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
app:
  mail:
    from:
    system:
api:
  crl: http://127.0.0.1:3001/api/crl
  ocsp: http://127.0.0.1:3002/api/ocsp
  x509: http://127.0.0.1:3003/api/x509
  ssh: http://127.0.0.1:3004/api/openssh
logging:
  file:
    path: ./
    name: info.log
  level:
    root: info
    sql: info
    web: info