override:
  server:
    port: 7011
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.10.100:3306/pki_master
  logging:
    file:
      path: /opt/apps/pki-master/
      name: pki-api-aia.log