override:
  server:
    port: 7012
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/pki_master
  logging:
    file:
      path: /opt/apps/pki-master/
      name: pki-api-crl.log