server:
  port: ${OVERRIDE_SERVER_PORT}
webui:
  servlet:
    load-on-startup: 1
    path: /*
  configuration-type: DEPLOYMENT
  wicket-factory: com.senior.cyber.pki.web.factory.WicketFactory
  pkg: com.senior.cyber.pki.web.pages
  admin-lte: ${OVERRIDE_ADMIN_LTE}
  csrf: false
pki:
  api:
    address:
      - ${OVERRIDE_PKI_API_URL}
spring:
  jpa:
    properties:
      hibernate:
        dialect: ${OVERRIDE_DB_DIALECT}
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mvc:
    servlet:
      path: /api
      load-on-startup: 1
  datasource:
    username: ${OVERRIDE_DB_UID}
    password: ${OVERRIDE_DB_PWD}
    driver-class-name: ${OVERRIDE_DB_DRIVER}
    url: jdbc:mysql://${OVERRIDE_DB_HOST}:${OVERRIDE_DB_PORT}/${OVERRIDE_DB_NAME}
  flyway:
    locations: classpath:com/senior/cyber/pki/dao/flyway
app:
  mode: Individual
  secret: 123123a
crypto:
  iv: Lxomdim3thxLYtOu8NmaXg==
logging:
  file:
    path: ${OVERRIDE_LOG_FILE_PATH}
    name: ${OVERRIDE_LOG_FILE_NAME}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR