override_server_port: 5080
override_db_url: jdbc:mysql://localhost:3306/pki_master
override_db_uid: root
override_db_pwd: password
override_db_driver: com.mysql.cj.jdbc.driver
override_db_dialect: org.hibernate.dialect.mysql8dialect
override_admin_lte: /opt/colorlibhq/adminlte
override_pki_api_url: http://localhost:4080
override_log_file_path: /opt/apps/pki-master
override_log_file_name: pki-web.log
