server:
  port: 3004
api:
  aia: http://aia.pki.khmer.name/api
  crl: http://crl.pki.khmer.name/api
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    database-platform: com.senior.cyber.pki.dao.dialect.MySQLDialect
  mvc:
    servlet:
      path: /
      load-on-startup: 1
  web:
    resources:
      static-locations:
        - 'file:/Users/socheatkhauv/code/github/senior-cyber/pki-master/pki-issuer-web/src/main/resources/public/'
  #        - 'file:/home/socheat/gitlab/socheat/survey/src/main/resources/public/'
  #        - 'classpath:/public/'
  thymeleaf:
    prefix: 'file:/Users/socheatkhauv/code/github/senior-cyber/pki-master/pki-issuer-web/src/main/resources/templates/'
    #    prefix: 'file:/home/socheat/gitlab/socheat/survey/src/main/resources/templates/'
    #    prefix: 'classpath:/templates/'
    cache: false
  messages:
    encoding: UTF-8

  datasource:
    username: root
    password: 123123a
    url: jdbc:mysql://192.168.1.53:3306/rootca
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:com/senior/cyber/pki/dao/flyway
app:
  mode: Individual
  secret: 123123a
crypto:
  iv: Lxomdim3thxLYtOu8NmaXg==
logging:
  file:
    path: /opt/apps/pki/pki-issuer-web
    name: info.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    sql: info
    web: info