server:
  port: 3004
webui:
  servlet:
    load-on-startup: 1
    path: /*
  configuration-type: DEPLOYMENT
  wicket-factory: com.senior.cyber.pki.issuer.web.factory.WicketFactory
  pages: com.senior.cyber.pki.issuer.web.pages
  admin-lte: /opt/apps/admin-lte
  csrf: false
api:
  aia: http://aia.pki.khmer.name/api
  crl: http://crl.pki.khmer.name/api
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    database-platform: com.senior.cyber.pki.dao.dialect.MySQLDialect
  mvc:
    servlet:
      path: /api
      load-on-startup: 1
  datasource:
    username: root
    password: 123123a
    url: jdbc:mysql://127.0.0.1:3306/rootca
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:com/senior/cyber/pki/dao/flyway
app:
  mode: Individual
  secret: 123123a
crypto:
  iv: Lxomdim3thxLYtOu8NmaXg==
logging:
  file:
    path: /opt/apps/pki/pki-issuer-web
    name: info.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    sql: info
    web: info