override:
  server:
    port: 8022
  webui:
    admin-lte: /Volumes/code/github/ColorlibHQ/v3
  api:
    aia: http://localhost:7011/api
    crl: http://localhost:7012/api
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/pki_master
  logging:
    file:
      path: /opt/apps/pki-master/
      name: pki-issuer-web.log
