server:
  port: 3003
  error:
    include-message: always
  address: 0.0.0.0
spring:
  application:
    name: Certificate Repository
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  mvc:
    servlet:
      path: /api
      load-on-startup: 1
  datasource:
    username: root
    password: 123123a
    url: jdbc:mysql://192.168.1.54:33088/pki
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db-migration
    clean-disabled: false
    validate-on-migrate: true
  session:
    jdbc:
      save-mode: always
      flush-mode: immediate
      cleanup-cron: 0 * * * * *
      initialize-schema: never
      table-name: tbl_cluster_SPRING_SESSION
      platform: mysql
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
api:
  crl: http://192.168.1.54:3001/api
  ocsp: http://192.168.1.54:3002/api
  x509: http://192.168.1.54:3003/api
  ssh: http://192.168.1.54:3004/api
logging:
  file:
    path: ./
    name: info.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    sql: info
    web: info